sudo: required
services:
    -docker

before_install:
    - docker build -t adityakumarsingh88/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run adityakumarsingh88/react-test npm test -- --coverage

after_success:
    - docker build -t adityakumarsingh88/multi_client ./client
    - docker build -t adityakumarsingh88/multi_nginx ./nginx
    - docker build -t adityakumarsingh88/multi_server ./server
    - docker build -t adityakumarsingh88/multi_worker ./worker
#Login to docker
    - echo $DOCKER_PASSWORD | docker login "$DOCKER_ID" --password-stdin
    - docker push adityakumarsingh88/multi_client
    - docker push adityakumarsingh88/multi_nginx
    - docker push adityakumarsingh88/multi_server
    - docker push adityakumarsingh88/multi_worker
    