
language: generic
sudo: required
services:
    -docker

before_install:
    - docker build -t adityakumarsingh88/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true adityakumarsingh88/react-test npm test

after_success:
    - docker build -t adityakumarsingh88/multi_client ./client
    - docker build -t adityakumarsingh88/multi_nginx ./nginx
    - docker build -t adityakumarsingh88/multi_server ./server
    - docker build -t adityakumarsingh88/multi_worker ./worker
#Login to docker
    - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
#Pushing tags to docker
    - docker push adityakumarsingh88/multi_client
    - docker push adityakumarsingh88/multi_nginx
    - docker push adityakumarsingh88/multi_server
    - docker push adityakumarsingh88/multi_worker
    